name: Build ZMK firmware

on:
  push:
    branches: [ main, pkkblab ] # 包含你的分支名
  workflow_dispatch: # 必须保留这一行，才能手动触发]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.2
